package rng

import (
	"bytes"
	"testing"
)

func Test_GenerateBytes_WithZeroLength_ReturnsEmptyArray(t *testing.T) {
	length := 0
	expected := make([]byte, 0)

	actual := GenerateBytes(length)

	if !bytes.Equal(expected, actual) {
		t.Error("Expected:", expected, "Actual:", actual)
	}
}

func Test_GenerateBytes_WithTenAsLength_ReturnsArrayWithTenBytes(t *testing.T) {
	length := 10

	actual := GenerateBytes(length)

	if len(actual) != length {
		t.Error("Expected length:", length, "Actual length:", len(actual))
	}
}

func Test_GenerateBytes_WithSameLength_ReturnsDifferentArrays(t *testing.T) {
	length := 10

	result1 := GenerateBytes(length)
	result2 := GenerateBytes(length)

	if bytes.Equal(result1, result2) {
		t.Error("Randomly generated bytes were expected to differ.")
	}
}
